openapi: 3.0.3
info:
  title: Public API — Лендинг мероприятия (публичный просмотр)
  version: 1.0.0
  description: Публичные эндпоинты для просмотра лендинга и перехода по ссылке "Я пойду". Авторизация для RSVP через email-код (тот же механизм, что и в мобильном API).
servers:
  - url: https://api.yourdomain.com/public
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    PublicEventInfo:
      type: object
      properties:
        id:
          type: string
          format: uuid
        title:
          type: string
        description:
          type: string
        bannerUrl:
          type: string
        shortInfo:
          type: string
paths:
  /events/{id}:
    get:
      summary: "Получить публичную информацию о мероприятии (лендинг preview)"
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: "Инфо лендинга"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PublicEventInfo'
        '404':
          description: "Не найдено или скрыто"
  /events/{id}/rsvp:
    post:
      summary: "Кнопка 'Я пойду' — инициирует авторизацию по email (тот же механизм как в mobile)"
      description: "Шаг 1: вызывает отправку кода. Клиент использует /auth/request-code затем /auth/verify-code; после успешной верификации пользователь получает токен и может просмотреть мероприятие."
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [email]
              properties:
                email:
                  type: string
                  format: email
      responses:
        '200':
          description: "Код для подтверждения отправлен"
        '404':
          description: "Мероприятие недоступно"
  /auth/request-code:
    post:
      summary: "Запрос кода на email (для посетителя лендинга)"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [email]
              properties:
                email:
                  type: string
                  format: email
      responses:
        '200':
          description: "Код отправлен"
  /auth/verify-code:
    post:
      summary: "Верификация кода (после /auth/request-code) — выдает JWT"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [email, code]
              properties:
                email:
                  type: string
                  format: email
                code:
                  type: string
      responses:
        '200':
          description: "Токен выдан"
          content:
            application/json:
              schema:
                type: object
                properties:
                  accessToken:
                    type: string
                  tokenType:
                    type: string
                    example: Bearer
        '401':
          description: "Неверный код"
tags:
  - name: public
  - name: auth
