openapi: 3.0.3
info:
  title: Admin API — Конструктор мероприятий (админка)
  version: 1.0.0
  description: API для веб-конструктора (панели администрирования). Доступ по логину/паролю (JWT).
servers:
  - url: https://api.yourdomain.com/admin
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Error:
      type: object
      properties:
        code:
          type: integer
        message:
          type: string
    AuthRequest:
      type: object
      required: [email, password]
      properties:
        email:
          type: string
          format: email
        password:
          type: string
    AuthResponse:
      type: object
      properties:
        accessToken:
          type: string
        tokenType:
          type: string
          example: Bearer
        expiresIn:
          type: integer
    TimelineEvent:
      type: object
      required: [id, time, title]
      properties:
        id:
          type: string
          format: uuid
        time:
          type: string
          format: date-time
        title:
          type: string
        description:
          type: string
    Point:
      type: object
      required: [id, x, y]
      properties:
        id:
          type: string
          format: uuid
        x:
          type: number
        y:
          type: number
        iconUrl:
          type: string
        content:
          type: string
    Event:
      type: object
      required: [id, title, description, visibility]
      properties:
        id:
          type: string
          format: uuid
        title:
          type: string
        description:
          type: string
        imageUrl:
          type: string
        visibility:
          type: string
          enum: [public, private]
        mapUrl:
          type: string
          description: "URL к SVG-карте (zoomable)"
          example: "file:///mnt/data/A_Use_Case_Diagram_illustrates_an_event_management.png"
        timeline:
          type: array
          items:
            $ref: '#/components/schemas/TimelineEvent'
        points:
          type: array
          items:
            $ref: '#/components/schemas/Point'
paths:
  /auth/login:
    post:
      summary: "Логин администратора (email + password)"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthRequest'
      responses:
        '200':
          description: "Успешная авторизация"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
        '401':
          description: "Неверные креды"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /events:
    post:
      summary: "Создать мероприятие"
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [title, description]
              properties:
                title:
                  type: string
                description:
                  type: string
                imageUrl:
                  type: string
                visibility:
                  type: string
                  enum: [public, private]
      responses:
        '201':
          description: "Мероприятие создано"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Event'
        '400':
          description: "Ошибка в данных"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /events/{id}:
    get:
      summary: "Получить мероприятие (по id)"
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: "Мероприятие"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Event'
    put:
      summary: "Обновить мероприятие"
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
                imageUrl:
                  type: string
                visibility:
                  type: string
                  enum: [public, private]
                timeline:
                  type: array
                  items:
                    $ref: '#/components/schemas/TimelineEvent'
                points:
                  type: array
                  items:
                    $ref: '#/components/schemas/Point'
      responses:
        '200':
          description: "Обновлённое мероприятие"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Event'
    delete:
      summary: "Удалить мероприятие"
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: "Удалено"
        '404':
          description: "Не найдено"
  /events/{id}/map/upload:
    post:
      summary: "Загрузить SVG-карту мероприятия (вариант A)"
      description: "multipart/form-data: поле file — SVG. Сохраняет mapUrl в мероприятии."
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        '200':
          description: "Карта загружена и связана с мероприятием"
          content:
            application/json:
              schema:
                type: object
                properties:
                  mapUrl:
                    type: string
                    example: "https://cdn.yourdomain.com/maps/event-<id>.svg"
        '400':
          description: "Ошибка загрузки"
  /events/{id}/publish:
    post:
      summary: "Опубликовать мероприятие (деплой лендинга и выставление видимости)"
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: "Опубликовано"
          content:
            application/json:
              schema:
                type: object
                properties:
                  url:
                    type: string
                    example: "https://domain.com/event/{id}"
        '500':
          description: "Ошибка деплоя"
  /events/{id}/visibility:
    put:
      summary: "Изменение доступности мероприятия"
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                visibility:
                  type: string
                  enum: [public, private]
      responses:
        '200':
          description: "Сохранено"
  /events/{id}/timeline:
    post:
      summary: "Добавить событие в таймлайн"
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TimelineEvent'
      responses:
        '201':
          description: "Добавлено"
  /events/{id}/points:
    post:
      summary: "Добавить интерактивную точку на карту"
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Point'
      responses:
        '201':
          description: "Точка добавлена"
tags:
  - name: auth
  - name: events
